version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=yourpassword  # Thay đổi mật khẩu quản trị viên
    networks:
      - monitor-network
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor-network

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - monitor-network

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - alertmanager-storage:/etc/alertmanager
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - monitor-network

networks:
  monitor-network:
    driver: bridge

volumes:
  grafana-storage:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/grafana/grafana-storage
      o: bind
  prometheus-storage:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/prometheus/prometheus-storage
      o: bind
  alertmanager-storage:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/alertmanager
      o: bind
